# Copyright 2023 Adevinta

name: Lava
description: Run Lava.
inputs:
  config:
    description: Path of the Lava configuration file.
  version:
    description: Lava version.
    default: latest
  forcecolor:
    description: Force colorized output.
    default: "true"
  comment-pr:
    description: Create a comment on pull request.
    default: "false"
outputs:
  status:
    description: Status code.
    value: ${{ steps.lava.outputs.status }}
  report:
    description: Path of the Lava report.
    value: ${{ steps.lava.outputs.report }}
  config:
    description: Path to the used Lava configuration file.
    value: ${{ steps.lava.outputs.config }}
  metrics:
    description: Path to the metrics generated file.
    value: ${{ steps.lava.outputs.metrics }}
runs:
  using: composite
  steps:
    - name: Run Lava
      id: lava
      run: '"${GITHUB_ACTION_PATH}/run.bash"'
      shell: bash
      env:
        LAVA_VERSION: ${{ inputs.version }}
        LAVA_CONFIG: ${{ inputs.config }}
        LAVA_FORCECOLOR: ${{ inputs.forcecolor }}
    - name: Write summary
      uses: actions/github-script@v7
      if: ${{ !cancelled() }}
      env:
        METRICS: ${{ steps.lava.outputs.metrics }}
        COMMENT_PR: ${{ inputs.comment-pr }}
      with:
        script: |
          const report = require(`${process.env.GITHUB_ACTION_PATH}/report.js`);
          await report.writeSummary(core);
    - name: Post comment
      uses: actions/github-script@v7
      if: ${{ !cancelled() && github.event_name=='pull_request' && inputs.comment-pr=='true' }}
      env:
        METRICS: ${{ steps.lava.outputs.metrics }}
      with:
        script: |
          const report = require(`${process.env.GITHUB_ACTION_PATH}/report.js`);
          await report.postComment(github, context, core);
