# Copyright 2023 Adevinta

name: Lava
description: Run Lava.
inputs:
  config:
    description: Path of the Lava configuration file.
  version:
    description: Lava version.
    default: latest
  forcecolor:
    description: Force colorized output.
    default: "true"
outputs:
  status:
    description: Status code.
    value: ${{ steps.lava.outputs.status }}
  report:
    description: Path of the Lava report.
    value: ${{ steps.lava.outputs.report }}
  config:
    description: Path to the used Lava configuration file.
    value: ${{ steps.lava.outputs.config }}
runs:
  using: composite
  steps:
    - name: Run Lava
      id: lava
      run: '"${GITHUB_ACTION_PATH}/run.bash"'
      shell: bash
      env:
        LAVA_VERSION: ${{ inputs.version }}
        LAVA_CONFIG: ${{ inputs.config }}
        LAVA_FORCECOLOR: ${{ inputs.forcecolor }}
