# Copyright 2023 Adevinta

name: Lava
description: Run Lava
inputs:
  config:
    description: Path of the Lava configuration file.
  version:
    description: Lava version.
    default: latest
  forcecolor:
    description: Force colorized output.
    default: true
outputs:
  status:
    description: Status code
    value: ${{ steps.lava.outputs.status }}
  report:
    description: Path of the Lava report
    value: ${{ steps.lava.outputs.report }}
runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Install Lava
      run: 'go install "github.com/adevinta/lava/cmd/lava@${{ inputs.version }}"'
      shell: bash
    - name: Run Lava
      id: lava
      run: '"${GITHUB_ACTION_PATH}/run.bash"'
      shell: bash
      env:
        LAVA_CONFIG: ${{ inputs.config }}
        LAVA_FORCECOLOR: ${{ inputs.forcecolor }}
