# Copyright 2023 Adevinta

lava: v0.0.0
logLevel: error
checktypesURLs:
  - https://github.com/adevinta/lava-resources/releases/download/checktypes/v0/checktypes.json
targets:
  - identifier: .
    assetType: GitRepository
agent:
  parallel: 4
report:
  severity: high
